import bcrypt from 'bcrypt';
import { User, UserRole, UserStatus, KycStatus } from '../models';

const SALT_ROUNDS = 10;

export async function seedUsers() {
  console.log('Seeding users...');

  const passwordHash = await bcrypt.hash('Password@123', SALT_ROUNDS);

  const users = [
    // Admin
    {
      email: 'admin@clientfirstcapital.com',
      passwordHash,
      phone: '+971501000001',
      fullName: 'System Admin',
      firstName: 'System',
      lastName: 'Admin',
      role: UserRole.ADMIN,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
    },

    // Introducers
    {
      email: 'sarah.ahmed@gmail.com',
      passwordHash,
      phone: '+971501000010',
      fullName: 'Sarah Ahmed',
      firstName: 'Sarah',
      lastName: 'Ahmed',
      role: UserRole.INTRODUCER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
      referralCode: 'SARAH2025',
      address: {
        line1: 'Villa 12, Al Barsha South',
        city: 'Dubai',
        emirate: 'Dubai',
        country: 'UAE',
      },
    },
    {
      email: 'omar.khan@gmail.com',
      passwordHash,
      phone: '+971501000011',
      fullName: 'Omar Khan',
      firstName: 'Omar',
      lastName: 'Khan',
      role: UserRole.INTRODUCER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'Pakistan',
      referralCode: 'OMAR2025',
      address: {
        line1: 'Apt 304, Marina Tower',
        city: 'Dubai',
        emirate: 'Dubai',
        country: 'UAE',
      },
    },
    {
      email: 'fatima.hassan@gmail.com',
      passwordHash,
      phone: '+971501000012',
      fullName: 'Fatima Hassan',
      firstName: 'Fatima',
      lastName: 'Hassan',
      role: UserRole.INTRODUCER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
      referralCode: 'FATIMA2025',
    },
    {
      email: 'raj.patel@gmail.com',
      passwordHash,
      phone: '+971501000013',
      fullName: 'Raj Patel',
      firstName: 'Raj',
      lastName: 'Patel',
      role: UserRole.INTRODUCER,
      status: UserStatus.PENDING,
      kycStatus: KycStatus.SUBMITTED,
      nationality: 'India',
      referralCode: 'RAJ2025',
    },

    // Advisors
    {
      email: 'michael.ross@clientfirstcapital.com',
      passwordHash,
      phone: '+971501000020',
      fullName: 'Michael Ross',
      firstName: 'Michael',
      lastName: 'Ross',
      role: UserRole.ADVISOR,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UK',
      address: {
        line1: 'Office 801, DIFC Gate Building',
        city: 'Dubai',
        emirate: 'Dubai',
        country: 'UAE',
      },
    },
    {
      email: 'aisha.malik@clientfirstcapital.com',
      passwordHash,
      phone: '+971501000021',
      fullName: 'Aisha Malik',
      firstName: 'Aisha',
      lastName: 'Malik',
      role: UserRole.ADVISOR,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
    },
    {
      email: 'james.lee@clientfirstcapital.com',
      passwordHash,
      phone: '+971501000022',
      fullName: 'James Lee',
      firstName: 'James',
      lastName: 'Lee',
      role: UserRole.ADVISOR,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'Singapore',
    },

    // Customers
    {
      email: 'ahmed.alblooshi@gmail.com',
      passwordHash,
      phone: '+971501000030',
      fullName: 'Ahmed Al Blooshi',
      firstName: 'Ahmed',
      lastName: 'Al Blooshi',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
      emiratesId: '784-1990-1234567-1',
      dateOfBirth: new Date('1990-05-15'),
      address: {
        line1: 'Villa 45, Jumeirah',
        city: 'Dubai',
        emirate: 'Dubai',
        country: 'UAE',
      },
    },
    {
      email: 'priya.sharma@gmail.com',
      passwordHash,
      phone: '+971501000031',
      fullName: 'Priya Sharma',
      firstName: 'Priya',
      lastName: 'Sharma',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'India',
      dateOfBirth: new Date('1988-11-20'),
    },
    {
      email: 'david.wilson@gmail.com',
      passwordHash,
      phone: '+971501000032',
      fullName: 'David Wilson',
      firstName: 'David',
      lastName: 'Wilson',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UK',
      dateOfBirth: new Date('1985-03-10'),
    },
    {
      email: 'layla.mohammed@gmail.com',
      passwordHash,
      phone: '+971501000033',
      fullName: 'Layla Mohammed',
      firstName: 'Layla',
      lastName: 'Mohammed',
      role: UserRole.CUSTOMER,
      status: UserStatus.PENDING,
      kycStatus: KycStatus.IN_PROGRESS,
      nationality: 'UAE',
      dateOfBirth: new Date('1992-07-08'),
    },
    {
      email: 'chen.wei@gmail.com',
      passwordHash,
      phone: '+971501000034',
      fullName: 'Chen Wei',
      firstName: 'Chen',
      lastName: 'Wei',
      role: UserRole.CUSTOMER,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'China',
      dateOfBirth: new Date('1979-01-25'),
    },

    // Investors
    {
      email: 'khalid.almaktoum@invest.ae',
      passwordHash,
      phone: '+971501000040',
      fullName: 'Khalid Al Maktoum',
      firstName: 'Khalid',
      lastName: 'Al Maktoum',
      role: UserRole.INVESTOR,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UAE',
    },
    {
      email: 'richard.branson@invest.ae',
      passwordHash,
      phone: '+971501000041',
      fullName: 'Richard Sterling',
      firstName: 'Richard',
      lastName: 'Sterling',
      role: UserRole.INVESTOR,
      status: UserStatus.ACTIVE,
      kycStatus: KycStatus.APPROVED,
      nationality: 'UK',
    },
  ];

  const result = await User.insertMany(users);
  console.log(`  ✓ ${result.length} users seeded`);
  return result;
}
